### ISSUE TITLE
Outdated package information displayed on the *Packages* buffer 

### ISSUE THREAD

**Issue by Ndot** [xzz53/mu4e-alert#12]
When using "list-packages" and pressing RETURN on "mu4e-alert" the information displays the website as https://github.com/iqbalansari/mu4e-alert it would be nice if this could be updated to point to this repo since this is the official repo now, correct? 

I got a bit lost when I clone the repo and nothing matched what was installed on my machine.

Cheers

**Comment by xzz53** [comment]
Fixed, hope melpa will pick this up soon.
