### ISSUE TITLE
mu4e-alert--get-group is wrong for mu4e development version

### ISSUE THREAD

**Issue by antoine-levitt** [xzz53/mu4e-alert#8]
Not quite sure what's going on, but `(caar (plist-get mail :from))` gets me ":name" with the current mu4e master. `cadar` works fine.

**Comment by xzz53** [comment]
Hi! Did this start to happen recently (after specific mu4e master commit)?

**Comment by antoine-levitt** [comment]
I don't know, I just upgraded from 1.6 series to git master and noticed this

**Comment by xzz53** [comment]
Ok, seems like https://github.com/djcb/mu/commit/45aec819f627110c3169f78656324167036c833b is the suspect. I'll look at it over the weekend.

**Comment by xzz53** [comment]
Should be fixed now.

**Comment by antoine-levitt** [comment]
Thanks!
